### PR TITLE
Sl/syncplots

### PR DESCRIPTION
**Pull request by spencerlyon2**
This is my first attempt at #19.

I think it makes things quite a bit cleaner and easier to work with. I still need to improve support for api methods in the notebook display backend.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Many of the changes here are minor organizational changes. 

The key differences are found in `display.jl` and the files that it `include`s

**Comment by spencerlyon2** [comment]
This is working pretty well. Merging now.

**Comment by tbreloff** [comment]
Hey @spencerlyon2 ... do you know how hard it will be to get this working with Plots again?  I assume it's just a few small changes but you'd know best.

**Comment by spencerlyon2** [comment]
Shouldn't be too hard. 

I can see you've started working on this. Please reach out if you need a hand.

**Pull request merged**
