### PR TITLE
Update REQUIRE

### PR DESCRIPTION
**Pull request by cc7768**

### CODE REVIEW

**Comment by cc7768** [comment]
Wait to accept. Looks like colors is needed as well.

**Comment by cc7768** [comment]
That should do it.

**Comment by spencerlyon2** [comment]
I don't depend on `Mux` directly. This should be in the REQUIRE for Blink.jl

I definitely do need the Colors one though

**Comment by cc7768** [comment]
Ah. Well this PR is very poorly named then...

**Comment by spencerlyon2** [comment]
See JunoLab/Blink.jl#15

**Comment by spencerlyon2** [comment]
Squashed for you, thanks

**Pull request merged**
