### PR TITLE
Rename

### LINKED ISSUE #9: Rename to PlotlyJS.jl
To be consistent with ThreeJS.jl and set a naming convention for Julia interfaces with JS APIs.

### PR DESCRIPTION
**Pull request by EricForgy**
I'm still learning GitHub but throwing this to you hoping it saves you some time.

Closes #9

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Thanks! merged with 412f180c5a7dee2a6c28a6a9212be8b81bb772f9

**Comment by EricForgy** [comment]
I notice Git on Windows sometimes has upper/lower case issues. Locally, I changed the file Plotlyjs.jl to PlotlyJS.jl, but it looks like it is still lowercase JS. Not a big I think, but maybe good to try to fix it

**Comment by EricForgy** [comment]
PS: I did not test it :D

**Comment by EricForgy** [comment]
All examples work and it looks great :D :+1:

**Comment by spencerlyon2** [comment]
Awesome, thanks for reporting. They also worked for me so that's a good thing!

**Pull request closed without merging**
