### PR TITLE
Fixes for Julia 0.5

### PR DESCRIPTION
**Pull request by timholy**
This fixes deprecation warnings and errors with Julia 0.5. Getting the tests working was also the occasion for fixing two julia bugs, https://github.com/JuliaLang/julia/pull/17966 and https://github.com/JuliaLang/julia/pull/17968. This won't pass tests on 0.5 until those are backported, but the tests do pass for me locally.

### CODE REVIEW

**Comment by timholy** [comment]
That second issue has morphed into "don't call `map` on a `Dict` unless your function returns a `Pair`." So I modified this a bit.

**Comment by timholy** [comment]
The travis error was fixed by JuliaLang/julia#17966, but that obviously hasn't made it to nightly yet.

**Comment by spencerlyon2** [comment]
Thanks for doing this!

**Comment by spencerlyon2** [comment]
And I'm happy my tests could expose bugs in base!

**Pull request merged**
