### PR TITLE
Added capability to resize the plot along with the electron display

### PR DESCRIPTION
**Pull request by mirestrepo**
The default behavior is to resize the plot as the electron window is being resized. To turn it off, the used just needs to define in in Main

ELECTRON_FIXED_SIZE_PLOT= true

### CODE REVIEW

**Comment by spencerlyon2** [comment]
HI @mirestrepo thank you for doing this.

I originally removed this functionality because I wanted the display of the plot to match the width and height settings in the plot's layout. I still feel that this should be the default behavior. 

As for API on how to do this I have a couple more alternatives (I'm listing them here not because I think they are superior to what was implemented, but rather I want to make sure we consider all the possibilities):

- Add a global in the `PlotlyJS` module. I think your explanation for choosing `Main` instead is pretty compelling so I don't think this is the right answer.
- Add a function `toggle_autoresize()` that will toggle the global variable, so the users don't have to think about the global themselves. We could also have `toggle_autoresize(::Bool)` that sets the global to the bool
- Have a function `autoresize!(::ElectronPlot)` that will update the display to start auto-resizing. 
- Add a checkbox kind of button to the menu bar up top that toggles the auto-resizing. 

I really don't know which option is the best, does anyone else have opinions on which way we should do this?

**Comment by tbreloff** [comment]
My opinion is that auto-resizing as the default is desirable.  You can have both an environment variable, and a "toggle" method which sets that environment variable, and have the best of all worlds (IMO)

**Comment by spencerlyon2** [comment]
I also like the idea of having the plot auto resize by defualt. 

Maybe a good solution would be to have the default be that the initial width and height are set by the layout attributes, but the autoresize would be active after that. Thoughts?

**Comment by tbreloff** [comment]
Yes Spencer that would be best.

**Comment by mirestrepo** [comment]
Any further resolutions on this? Implementing the function to toggle the global  is easy. That is what I was initially doing before opting for putting the global in Main scope. I think that is great solution as well and I agree that having the autoresizing as the default is more natural. @spencerlyon2  Would  like me to implant the toggle function? are there any other concerns?

**Comment by spencerlyon2** [comment]
Sorry, I've been extra busy lately and haven't had time for pushing this forward. I'm hoping things will settle down soon.

If you are willing to add a function that toggles a global in the PlotlyJS namespace that'd be great.

It is typical to have such globals be defined as  a one element vector as follows:

```julia
const autoresize = [true]
```

Doing so allows us to change the value of the variable, but let's the comiler treat the `autoresize` as a constant that always has type `Vector{Bool}`. We'd simply read and write to `autoresize[1]`.

Thanks!

**Comment by mirestrepo** [comment]
Perfect, I'll try to get to it later today or tomorrow. Thanks for the hint about the global - it's good to know!

**Comment by spencerlyon2** [comment]
Implemented and merged here: da9ed228cba3449937badb3402d69d08062fff80

Thank you for getting this started!

**Comment by mirestrepo** [comment]
Awesome! Sorry, I din't get to it - work got busy and the travels came around. Thanks for adding the implementation

**Pull request closed without merging**
